version: '3'
services:
    alphp:
        image: swoft/alphp:fpm
        container_name: php-svr
        environment:
            - APP_ENV=prod
        links:
            - mysql
            - redis
        ports:
            - "80:80"
            - "443:443"
            - "9501:9501"
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/conf.d:/etc/nginx/conf.d
            - /data/www:/data/www
            - /data/www/logs/nginx:/var/log

    mysql:
        image: mysql:latest
        container_name: mysql-svr
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "3306:3306"
        volumes:
            - /data/www/mysql:/var/lib/mysql
            - /data/www/logs/mysql:/var/log/mysql

    redis:
        container_name: redis-svr
        image: redis:4-alpine
        ports:
            - "6379:6379"
